# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('machine', models.TextField(default='')),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemporaryToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('editor', models.BooleanField(default=False)),
                ('viewer', models.BooleanField(default=False)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_tokens', to='base.AccessToken')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
