# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-05 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytoken',
            name='_primary',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
