# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_user_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_email_key_returned',
            field=models.BooleanField(default=False),
        ),
    ]
